services:
  db:
    image: postgres:17.4
    environment:
      POSTGRES_USER: usuario 
      POSTGRES_PASSWORD: 123 
      POSTGRES_DB: mydb 
    ports:
      - "5439:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts:/etc/scripts/

volumes:
  pgdata:
