x-template:
  &template
  depends_on:
    - redis
  environment:
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - REDIS_PASSWORD=local

services:
  consumer:
    <<: *template
    image: consumer:local 
    build:
      context: .
      dockerfile: Consumer.dockerfile
    container_name: "consumer"
    # FIXIT workaround para o consumidor iniciar apos o produtor
    # Eh necessario corrigir isso na implementacao do consumidor
    depends_on:
      - producer

  producer:
    <<: *template
    image: producer:local
    build:
      context: .
      dockerfile: Producer.dockerfile
    container_name: "producer"

  redis:
    image: "redis:alpine"
    container_name: "redis"
    command: redis-server --requirepass local 
    ports:
      - "6379:6379"